### ISSUE TITLE
Name mismatch reported for "VIEW" and "VW"

### ISSUE THREAD

**Issue by dobratzp** [mharnold/spiderosm#20]
On the [portland map](http://names.mhaprojects.com/portland.html) there is a street "Southwest Westwood View" which is reported as a mismatch.

city: SW WESTWOOD VW
osm: SW WESTWOOD VIEW

See the following OSM Ways:

http://www.openstreetmap.org/way/5519050
http://www.openstreetmap.org/way/144133955

This should not be reported as a mismatch.

**Comment by mharnold** [comment]
Thanks for the bug report.

The latest version of spiderOSM (v0.4.1) added more comprehensive street
type abbreviations, including VIEW -> VW, to the name processing.  So the
above should be fixed when I switch the map updating to the latest version
of spiderOSM.

Cheers,
Michael
spiderOSM.org

**Comment by mharnold** [comment]
I've upgraded the name map update software to spiderosm v0.4.1.  Checked the portland map after running and SW WESTWOOD VW is no longer marked as an error.
