### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by ryanpeterson08** [mharnold/spiderosm#21]
I've been trying to run the spiderosm_portland.py on my windows desktop, it runs for awhile and seems like it is close to finishing , but then it always throws an error reading "MemoryError".  I have modified the script to just have a bounding box around the Beaverton area (suburb of Portland) and it works fine.

I think the specs on my Computer should be able to handle it, just wondering if anyone else has run into a similar problem when running on spiderosm over larger bounding boxes.

![memoryerror](https://cloud.githubusercontent.com/assets/8027982/5928867/5ed679dc-a633-11e4-895d-f2e5ec0c840a.jpg)

**Comment by mharnold** [comment]
Looks like spiderOSM had finished matching the city and osm networks and died during output of the result.  Frustrating!  Possibly a second in memory copy of the network is effectively generated prior to output.   I will look into removing such a bottleneck.

Have you checked if you have  a per-process memory limit you can raise?  (I don't know the Windows OS myself.)  Also does your machine have 32 or 64 bit addresses?

**Comment by mharnold** [comment]
I rewrote geojson output for pnwks so it does not first generate an entire geojson style version of the network in memory (spiderosm v 0.4.2)  This should (hopefully) fix your problem.  Though probably I now need to make reading the network back incremental too! 

Ryan, can you please give the new version of spiderosm a try and let me know what happens?

**Comment by ryanpeterson08** [comment]
I will look in the pre-process memory limit, and my machine is a 64-bit machine.  I will give spiderosm 0.4.2 a go.

**Comment by ryanpeterson08** [comment]
Got it to work, the issue was that I didn't realize I was running a 32-bit python on my machine.  Installed the 64-bit version and it worked fine.

**Comment by mharnold** [comment]
Makes sense!   I see "32 bit" in the sys.version string of "config info" in your screen dump.
