### ISSUE TITLE
geojson output broken (not readable by qgis) in 0.4.2

### ISSUE THREAD

**Issue by mharnold** [mharnold/spiderosm#22]
Looks like I broke geojson output in v0.4.2?

I will look at this soon.  In the meantime, backing out to v0.4.1 probably works:
%pip uninstall spiderosm
%pip install spiderosm==0.4.1

**Comment by ryanpeterson08** [comment]
I got it to work, it was an issue on my end (not having the 64-bit version of QGIS)

**Comment by mharnold** [comment]
OK Thanks Ryan!  So geojson output in spiderosm v0.4.2 works, but large files like the path networks for portland, may not be readable from 32-bit QGIS executables.
