### ISSUE TITLE
Portland map returns 403 Forbidden

### ISSUE THREAD

**Issue by dobratzp** [mharnold/spiderosm#23]
http://names.mhaprojects.com/portland.html

returns HTTP: 403 Forbidden.

**Comment by mharnold** [comment]
Thanks Peter!  I've backed out  to an older version.  Will fix the
permissions problem for real later today.

Cheers,
Michael
spiderOSM.org

**Comment by mharnold** [comment]
Added 'fix permissions' code to website build to prevent recurrence of this problem.
